openapi: 3.0.3
info:
  title: 'BlueRockTEL Admin API'
  version: '1.0'
  description: 'Documentation for the BlueRockTEL Admin API'
  contact: 
    name: BlueRockTEL API Team
    url: https://api-admin.bluerocktel.com
    email: team-api@bluerocktel.com
servers:
  - url: 'https://telecom0558-admin.bluerocktel.net'
    description: 'API Demo Server'
